# topics
publish_velocity: true
publish_encoder:  true
publish_current:  true
publish_motor_joint_state: false
update_rate: 100.0
# motor model
motor_nominal_voltage: 12.0 # Volts
moment_of_inertia: 0.01 # kgm^2
armature_damping_ratio: 0.03 # Nm/(rad/s)
electromotive_force_constant: 0.03 # Nm/A
electric_resistance: 6.0 # Ohm
electric_inductance: 0.001 # Henry
# transmission
gear_ratio: 18.0
joint_damping: 0.005
joint_friction: 0.01
# shaft encoder
encoder_ppr: 50
